"""
unique constraint on game_date per table

Revision ID: 3fdd8c8b6626
Revises: 4ba93a4854fb
Create Date: 2026-08-26 23:44:47.606956

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3fdd8c8b6626"
down_revision: str | Sequence[str] | None = "4ba93a4854fb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "baloto_draws",
        "game_date",
        existing_type=sa.DATE(),
        comment="Calendar date the draw was held; unique per game.",
        existing_comment="Calendar date the draw was held.",
        existing_nullable=False,
    )
    op.create_unique_constraint("uq_baloto_draws_game_date", "baloto_draws", ["game_date"])
    op.alter_column(
        "miloto_draws",
        "game_date",
        existing_type=sa.DATE(),
        comment="Calendar date the draw was held; unique per game.",
        existing_comment="Calendar date the draw was held.",
        existing_nullable=False,
    )
    op.create_unique_constraint("uq_miloto_draws_game_date", "miloto_draws", ["game_date"])
    op.alter_column(
        "revancha_draws",
        "game_date",
        existing_type=sa.DATE(),
        comment="Calendar date the draw was held; unique per game.",
        existing_comment="Calendar date the draw was held.",
        existing_nullable=False,
    )
    op.create_unique_constraint("uq_revancha_draws_game_date", "revancha_draws", ["game_date"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_revancha_draws_game_date", "revancha_draws", type_="unique")
    op.alter_column(
        "revancha_draws",
        "game_date",
        existing_type=sa.DATE(),
        comment="Calendar date the draw was held.",
        existing_comment="Calendar date the draw was held; unique per game.",
        existing_nullable=False,
    )
    op.drop_constraint("uq_miloto_draws_game_date", "miloto_draws", type_="unique")
    op.alter_column(
        "miloto_draws",
        "game_date",
        existing_type=sa.DATE(),
        comment="Calendar date the draw was held.",
        existing_comment="Calendar date the draw was held; unique per game.",
        existing_nullable=False,
    )
    op.drop_constraint("uq_baloto_draws_game_date", "baloto_draws", type_="unique")
    op.alter_column(
        "baloto_draws",
        "game_date",
        existing_type=sa.DATE(),
        comment="Calendar date the draw was held.",
        existing_comment="Calendar date the draw was held; unique per game.",
        existing_nullable=False,
    )
    # ### end Alembic commands ###
