"""
add game draw tables

Revision ID: 4ba93a4854fb
Revises:
Create Date: 2026-08-26 22:22:12.222006

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "4ba93a4854fb"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "baloto_draws",
        sa.Column("super_balota", sa.SmallInteger(), nullable=False, comment="The drawn super balota (bonus) number."),
        sa.Column(
            "hits_sb", postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment="Super-balota-only payout tier."
        ),
        sa.Column(
            "hits_2_sb",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="2-hits + super-balota payout tier.",
        ),
        sa.Column(
            "hits_3_sb",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="3-hits + super-balota payout tier.",
        ),
        sa.Column(
            "hits_4_sb",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="4-hits + super-balota payout tier.",
        ),
        sa.Column(
            "hits_5_sb",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="5-hits + super-balota payout tier (the jackpot).",
        ),
        sa.Column(
            "game_id",
            sa.Integer(),
            nullable=False,
            comment="Official draw number ('Sorteo'), unique per game and assigned by the operator.",
        ),
        sa.Column("game_date", sa.Date(), nullable=False, comment="Calendar date the draw was held."),
        sa.Column(
            "numbers",
            postgresql.ARRAY(sa.SmallInteger()),
            nullable=False,
            comment="The 5 winning numbers, ascending and unique, as validated by app.games.schemas.",
        ),
        sa.Column(
            "accumulated",
            sa.BigInteger(),
            nullable=False,
            comment="Accumulated jackpot for this draw, in Colombian pesos.",
        ),
        sa.Column(
            "combination_id",
            sa.String(),
            nullable=False,
            comment="Hex bitmap identifying the winning-number combination; see app.shared.math_utils.numbers_to_hex.",
        ),
        sa.Column(
            "hits_3",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="3-hits payout tier: {'prize_for_winner': int, 'winners': int}, or null.",
        ),
        sa.Column("hits_4", postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment="4-hits payout tier."),
        sa.Column("hits_5", postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment="5-hits payout tier."),
        sa.Column(
            "scraped_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="When this row was first inserted by the scraper, not when the draw was held.",
        ),
        sa.PrimaryKeyConstraint("game_id"),
    )
    op.create_index(op.f("ix_baloto_draws_combination_id"), "baloto_draws", ["combination_id"], unique=False)
    op.create_table(
        "miloto_draws",
        sa.Column("hits_2", postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment="2-hits payout tier."),
        sa.Column(
            "game_id",
            sa.Integer(),
            nullable=False,
            comment="Official draw number ('Sorteo'), unique per game and assigned by the operator.",
        ),
        sa.Column("game_date", sa.Date(), nullable=False, comment="Calendar date the draw was held."),
        sa.Column(
            "numbers",
            postgresql.ARRAY(sa.SmallInteger()),
            nullable=False,
            comment="The 5 winning numbers, ascending and unique, as validated by app.games.schemas.",
        ),
        sa.Column(
            "accumulated",
            sa.BigInteger(),
            nullable=False,
            comment="Accumulated jackpot for this draw, in Colombian pesos.",
        ),
        sa.Column(
            "combination_id",
            sa.String(),
            nullable=False,
            comment="Hex bitmap identifying the winning-number combination; see app.shared.math_utils.numbers_to_hex.",
        ),
        sa.Column(
            "hits_3",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="3-hits payout tier: {'prize_for_winner': int, 'winners': int}, or null.",
        ),
        sa.Column("hits_4", postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment="4-hits payout tier."),
        sa.Column("hits_5", postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment="5-hits payout tier."),
        sa.Column(
            "scraped_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="When this row was first inserted by the scraper, not when the draw was held.",
        ),
        sa.PrimaryKeyConstraint("game_id"),
    )
    op.create_index(op.f("ix_miloto_draws_combination_id"), "miloto_draws", ["combination_id"], unique=False)
    op.create_table(
        "revancha_draws",
        sa.Column("super_balota", sa.SmallInteger(), nullable=False, comment="The drawn super balota (bonus) number."),
        sa.Column(
            "hits_sb", postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment="Super-balota-only payout tier."
        ),
        sa.Column(
            "hits_2_sb",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="2-hits + super-balota payout tier.",
        ),
        sa.Column(
            "hits_3_sb",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="3-hits + super-balota payout tier.",
        ),
        sa.Column(
            "hits_4_sb",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="4-hits + super-balota payout tier.",
        ),
        sa.Column(
            "hits_5_sb",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="5-hits + super-balota payout tier (the jackpot).",
        ),
        sa.Column(
            "game_id",
            sa.Integer(),
            nullable=False,
            comment="Official draw number ('Sorteo'), unique per game and assigned by the operator.",
        ),
        sa.Column("game_date", sa.Date(), nullable=False, comment="Calendar date the draw was held."),
        sa.Column(
            "numbers",
            postgresql.ARRAY(sa.SmallInteger()),
            nullable=False,
            comment="The 5 winning numbers, ascending and unique, as validated by app.games.schemas.",
        ),
        sa.Column(
            "accumulated",
            sa.BigInteger(),
            nullable=False,
            comment="Accumulated jackpot for this draw, in Colombian pesos.",
        ),
        sa.Column(
            "combination_id",
            sa.String(),
            nullable=False,
            comment="Hex bitmap identifying the winning-number combination; see app.shared.math_utils.numbers_to_hex.",
        ),
        sa.Column(
            "hits_3",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="3-hits payout tier: {'prize_for_winner': int, 'winners': int}, or null.",
        ),
        sa.Column("hits_4", postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment="4-hits payout tier."),
        sa.Column("hits_5", postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment="5-hits payout tier."),
        sa.Column(
            "scraped_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="When this row was first inserted by the scraper, not when the draw was held.",
        ),
        sa.PrimaryKeyConstraint("game_id"),
    )
    op.create_index(op.f("ix_revancha_draws_combination_id"), "revancha_draws", ["combination_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_revancha_draws_combination_id"), table_name="revancha_draws")
    op.drop_table("revancha_draws")
    op.drop_index(op.f("ix_miloto_draws_combination_id"), table_name="miloto_draws")
    op.drop_table("miloto_draws")
    op.drop_index(op.f("ix_baloto_draws_combination_id"), table_name="baloto_draws")
    op.drop_table("baloto_draws")
    # ### end Alembic commands ###
